const { Router } = require('express')
const c = require('../controllers/interview.controller')
const { authUser } = require('../middlewares/auth.middleware')
const upload = require('../middlewares/file.middleware')
const validate = require('../middlewares/validate.middleware')
const asyncHandler = require('../utils/asyncHandler')
const router = Router()

router.use(authUser)
router.post('/', upload.single('resume'), validate(c.reportSchema), asyncHandler(c.generateInterViewReportController))
router.get('/', asyncHandler(c.getAllInterviewReportsController))
router.get('/report/:interviewId', asyncHandler(c.getInterviewReportByIdController))
router.post('/report/:interviewId/assistant', validate(c.assistantSchema), asyncHandler(c.askAssistantController))
router.post('/resume/pdf/:interviewReportId', asyncHandler(c.generateResumePdfController))
module.exports = router
